/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: slot.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "slot.pb-c.h"
void   slot__init
                     (Slot         *message)
{
  static Slot init_value = SLOT__INIT;
  *message = init_value;
}
size_t slot__get_packed_size
                     (const Slot *message)
{
  assert(message->base.descriptor == &slot__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t slot__pack
                     (const Slot *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &slot__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t slot__pack_to_buffer
                     (const Slot *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &slot__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Slot *
       slot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Slot *)
     protobuf_c_message_unpack (&slot__descriptor,
                                allocator, len, data);
}
void   slot__free_unpacked
                     (Slot *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &slot__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   address__init
                     (Address         *message)
{
  static Address init_value = ADDRESS__INIT;
  *message = init_value;
}
size_t address__get_packed_size
                     (const Address *message)
{
  assert(message->base.descriptor == &address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t address__pack
                     (const Address *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t address__pack_to_buffer
                     (const Address *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Address *
       address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Address *)
     protobuf_c_message_unpack (&address__descriptor,
                                allocator, len, data);
}
void   address__free_unpacked
                     (Address *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ibid__init
                     (Ibid         *message)
{
  static Ibid init_value = IBID__INIT;
  *message = init_value;
}
size_t ibid__get_packed_size
                     (const Ibid *message)
{
  assert(message->base.descriptor == &ibid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ibid__pack
                     (const Ibid *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ibid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ibid__pack_to_buffer
                     (const Ibid *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ibid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ibid *
       ibid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ibid *)
     protobuf_c_message_unpack (&ibid__descriptor,
                                allocator, len, data);
}
void   ibid__free_unpacked
                     (Ibid *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ibid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   value__flag_id__init
                     (Value__FlagId         *message)
{
  static Value__FlagId init_value = VALUE__FLAG_ID__INIT;
  *message = init_value;
}
void   value__init
                     (Value         *message)
{
  static Value init_value = VALUE__INIT;
  *message = init_value;
}
size_t value__get_packed_size
                     (const Value *message)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t value__pack
                     (const Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t value__pack_to_buffer
                     (const Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Value *
       value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Value *)
     protobuf_c_message_unpack (&value__descriptor,
                                allocator, len, data);
}
void   value__free_unpacked
                     (Value *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scalar__init
                     (Scalar         *message)
{
  static Scalar init_value = SCALAR__INIT;
  *message = init_value;
}
size_t scalar__get_packed_size
                     (const Scalar *message)
{
  assert(message->base.descriptor == &scalar__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scalar__pack
                     (const Scalar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scalar__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scalar__pack_to_buffer
                     (const Scalar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scalar__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scalar *
       scalar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scalar *)
     protobuf_c_message_unpack (&scalar__descriptor,
                                allocator, len, data);
}
void   scalar__free_unpacked
                     (Scalar *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scalar__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uninitialized__init
                     (Uninitialized         *message)
{
  static Uninitialized init_value = UNINITIALIZED__INIT;
  *message = init_value;
}
size_t uninitialized__get_packed_size
                     (const Uninitialized *message)
{
  assert(message->base.descriptor == &uninitialized__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uninitialized__pack
                     (const Uninitialized *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &uninitialized__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uninitialized__pack_to_buffer
                     (const Uninitialized *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &uninitialized__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Uninitialized *
       uninitialized__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Uninitialized *)
     protobuf_c_message_unpack (&uninitialized__descriptor,
                                allocator, len, data);
}
void   uninitialized__free_unpacked
                     (Uninitialized *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &uninitialized__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   undefined__init
                     (Undefined         *message)
{
  static Undefined init_value = UNDEFINED__INIT;
  *message = init_value;
}
size_t undefined__get_packed_size
                     (const Undefined *message)
{
  assert(message->base.descriptor == &undefined__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t undefined__pack
                     (const Undefined *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &undefined__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t undefined__pack_to_buffer
                     (const Undefined *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &undefined__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Undefined *
       undefined__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Undefined *)
     protobuf_c_message_unpack (&undefined__descriptor,
                                allocator, len, data);
}
void   undefined__free_unpacked
                     (Undefined *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &undefined__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xs_null__init
                     (XsNull         *message)
{
  static XsNull init_value = XS_NULL__INIT;
  *message = init_value;
}
size_t xs_null__get_packed_size
                     (const XsNull *message)
{
  assert(message->base.descriptor == &xs_null__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xs_null__pack
                     (const XsNull *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xs_null__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xs_null__pack_to_buffer
                     (const XsNull *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xs_null__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
XsNull *
       xs_null__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (XsNull *)
     protobuf_c_message_unpack (&xs_null__descriptor,
                                allocator, len, data);
}
void   xs_null__free_unpacked
                     (XsNull *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &xs_null__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xs_complex__init
                     (XsComplex         *message)
{
  static XsComplex init_value = XS_COMPLEX__INIT;
  *message = init_value;
}
size_t xs_complex__get_packed_size
                     (const XsComplex *message)
{
  assert(message->base.descriptor == &xs_complex__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xs_complex__pack
                     (const XsComplex *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xs_complex__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xs_complex__pack_to_buffer
                     (const XsComplex *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xs_complex__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
XsComplex *
       xs_complex__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (XsComplex *)
     protobuf_c_message_unpack (&xs_complex__descriptor,
                                allocator, len, data);
}
void   xs_complex__free_unpacked
                     (XsComplex *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &xs_complex__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   array__init
                     (Array         *message)
{
  static Array init_value = ARRAY__INIT;
  *message = init_value;
}
size_t array__get_packed_size
                     (const Array *message)
{
  assert(message->base.descriptor == &array__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t array__pack
                     (const Array *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &array__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t array__pack_to_buffer
                     (const Array *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &array__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Array *
       array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Array *)
     protobuf_c_message_unpack (&array__descriptor,
                                allocator, len, data);
}
void   array__free_unpacked
                     (Array *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &array__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   reference__init
                     (Reference         *message)
{
  static Reference init_value = REFERENCE__INIT;
  *message = init_value;
}
size_t reference__get_packed_size
                     (const Reference *message)
{
  assert(message->base.descriptor == &reference__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reference__pack
                     (const Reference *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reference__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reference__pack_to_buffer
                     (const Reference *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reference__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Reference *
       reference__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Reference *)
     protobuf_c_message_unpack (&reference__descriptor,
                                allocator, len, data);
}
void   reference__free_unpacked
                     (Reference *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &reference__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   slot_opt__init
                     (SlotOpt         *message)
{
  static SlotOpt init_value = SLOT_OPT__INIT;
  *message = init_value;
}
size_t slot_opt__get_packed_size
                     (const SlotOpt *message)
{
  assert(message->base.descriptor == &slot_opt__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t slot_opt__pack
                     (const SlotOpt *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &slot_opt__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t slot_opt__pack_to_buffer
                     (const SlotOpt *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &slot_opt__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SlotOpt *
       slot_opt__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SlotOpt *)
     protobuf_c_message_unpack (&slot_opt__descriptor,
                                allocator, len, data);
}
void   slot_opt__free_unpacked
                     (SlotOpt *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &slot_opt__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   slot_list__init
                     (SlotList         *message)
{
  static SlotList init_value = SLOT_LIST__INIT;
  *message = init_value;
}
size_t slot_list__get_packed_size
                     (const SlotList *message)
{
  assert(message->base.descriptor == &slot_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t slot_list__pack
                     (const SlotList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &slot_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t slot_list__pack_to_buffer
                     (const SlotList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &slot_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SlotList *
       slot_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SlotList *)
     protobuf_c_message_unpack (&slot_list__descriptor,
                                allocator, len, data);
}
void   slot_list__free_unpacked
                     (SlotList *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &slot_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   none__init
                     (None         *message)
{
  static None init_value = NONE__INIT;
  *message = init_value;
}
size_t none__get_packed_size
                     (const None *message)
{
  assert(message->base.descriptor == &none__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t none__pack
                     (const None *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &none__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t none__pack_to_buffer
                     (const None *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &none__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
None *
       none__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (None *)
     protobuf_c_message_unpack (&none__descriptor,
                                allocator, len, data);
}
void   none__free_unpacked
                     (None *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &none__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nil__init
                     (Nil         *message)
{
  static Nil init_value = NIL__INIT;
  *message = init_value;
}
size_t nil__get_packed_size
                     (const Nil *message)
{
  assert(message->base.descriptor == &nil__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nil__pack
                     (const Nil *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nil__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nil__pack_to_buffer
                     (const Nil *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nil__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nil *
       nil__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nil *)
     protobuf_c_message_unpack (&nil__descriptor,
                                allocator, len, data);
}
void   nil__free_unpacked
                     (Nil *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nil__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   instance__init
                     (Instance         *message)
{
  static Instance init_value = INSTANCE__INIT;
  *message = init_value;
}
size_t instance__get_packed_size
                     (const Instance *message)
{
  assert(message->base.descriptor == &instance__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t instance__pack
                     (const Instance *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &instance__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t instance__pack_to_buffer
                     (const Instance *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &instance__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Instance *
       instance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Instance *)
     protobuf_c_message_unpack (&instance__descriptor,
                                allocator, len, data);
}
void   instance__free_unpacked
                     (Instance *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &instance__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   code__init
                     (Code         *message)
{
  static Code init_value = CODE__INIT;
  *message = init_value;
}
size_t code__get_packed_size
                     (const Code *message)
{
  assert(message->base.descriptor == &code__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t code__pack
                     (const Code *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &code__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t code__pack_to_buffer
                     (const Code *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &code__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Code *
       code__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Code *)
     protobuf_c_message_unpack (&code__descriptor,
                                allocator, len, data);
}
void   code__free_unpacked
                     (Code *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &code__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   accessor__init
                     (Accessor         *message)
{
  static Accessor init_value = ACCESSOR__INIT;
  *message = init_value;
}
size_t accessor__get_packed_size
                     (const Accessor *message)
{
  assert(message->base.descriptor == &accessor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t accessor__pack
                     (const Accessor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &accessor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t accessor__pack_to_buffer
                     (const Accessor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &accessor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Accessor *
       accessor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Accessor *)
     protobuf_c_message_unpack (&accessor__descriptor,
                                allocator, len, data);
}
void   accessor__free_unpacked
                     (Accessor *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &accessor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   home__init
                     (Home         *message)
{
  static Home init_value = HOME__INIT;
  *message = init_value;
}
size_t home__get_packed_size
                     (const Home *message)
{
  assert(message->base.descriptor == &home__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t home__pack
                     (const Home *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &home__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t home__pack_to_buffer
                     (const Home *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &home__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Home *
       home__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Home *)
     protobuf_c_message_unpack (&home__descriptor,
                                allocator, len, data);
}
void   home__free_unpacked
                     (Home *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &home__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   callback__init
                     (Callback         *message)
{
  static Callback init_value = CALLBACK__INIT;
  *message = init_value;
}
size_t callback__get_packed_size
                     (const Callback *message)
{
  assert(message->base.descriptor == &callback__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t callback__pack
                     (const Callback *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &callback__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t callback__pack_to_buffer
                     (const Callback *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &callback__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Callback *
       callback__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Callback *)
     protobuf_c_message_unpack (&callback__descriptor,
                                allocator, len, data);
}
void   callback__free_unpacked
                     (Callback *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &callback__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor slot__field_descriptors[12] =
{
  {
    "the_null",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Slot, kind_case),
    offsetof(Slot, the_null),
    &xs_null__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Slot, kind_case),
    offsetof(Slot, bool_),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integer",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Slot, kind_case),
    offsetof(Slot, integer),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Slot, kind_case),
    offsetof(Slot, number),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Slot, kind_case),
    offsetof(Slot, string),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbol",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Slot, kind_case),
    offsetof(Slot, symbol),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bigint",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Slot, kind_case),
    offsetof(Slot, bigint),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uninitialized",
    99,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Slot, kind_case),
    offsetof(Slot, uninitialized),
    &uninitialized__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "undefined",
    100,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Slot, kind_case),
    offsetof(Slot, undefined),
    &undefined__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next",
    200,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Slot, next),
    &address__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ID",
    201,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Slot, has_id),
    offsetof(Slot, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flag",
    203,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Slot, has_flag),
    offsetof(Slot, flag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slot__field_indices_by_name[] = {
  10,   /* field[10] = ID */
  6,   /* field[6] = bigint */
  1,   /* field[1] = bool */
  11,   /* field[11] = flag */
  2,   /* field[2] = integer */
  9,   /* field[9] = next */
  3,   /* field[3] = number */
  4,   /* field[4] = string */
  5,   /* field[5] = symbol */
  0,   /* field[0] = the_null */
  8,   /* field[8] = undefined */
  7,   /* field[7] = uninitialized */
};
static const ProtobufCIntRange slot__number_ranges[5 + 1] =
{
  { 1, 0 },
  { 7, 5 },
  { 99, 7 },
  { 200, 9 },
  { 203, 11 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor slot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Slot",
  "Slot",
  "Slot",
  "",
  sizeof(Slot),
  12,
  slot__field_descriptors,
  slot__field_indices_by_name,
  5,  slot__number_ranges,
  (ProtobufCMessageInit) slot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor address__field_descriptors[1] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Address, has_index),
    offsetof(Address, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned address__field_indices_by_name[] = {
  0,   /* field[0] = index */
};
static const ProtobufCIntRange address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Address",
  "Address",
  "Address",
  "",
  sizeof(Address),
  1,
  address__field_descriptors,
  address__field_indices_by_name,
  1,  address__number_ranges,
  (ProtobufCMessageInit) address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ibid__field_descriptors[2] =
{
  {
    "exit",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Ibid, tag_case),
    offsetof(Ibid, exit),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ibid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Ibid, tag_case),
    offsetof(Ibid, ibid),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ibid__field_indices_by_name[] = {
  0,   /* field[0] = exit */
  1,   /* field[1] = ibid */
};
static const ProtobufCIntRange ibid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ibid__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ibid",
  "Ibid",
  "Ibid",
  "",
  sizeof(Ibid),
  2,
  ibid__field_descriptors,
  ibid__field_indices_by_name,
  1,  ibid__number_ranges,
  (ProtobufCMessageInit) ibid__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor value__flag_id__field_descriptors[3] =
{
  {
    "flag",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Value__FlagId, has_flag),
    offsetof(Value__FlagId, flag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ID",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Value__FlagId, has_id),
    offsetof(Value__FlagId, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "IDname",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Value__FlagId, has_idname),
    offsetof(Value__FlagId, idname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned value__flag_id__field_indices_by_name[] = {
  1,   /* field[1] = ID */
  2,   /* field[2] = IDname */
  0,   /* field[0] = flag */
};
static const ProtobufCIntRange value__flag_id__number_ranges[1 + 1] =
{
  { 4, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor value__flag_id__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Value.FlagId",
  "FlagId",
  "Value__FlagId",
  "",
  sizeof(Value__FlagId),
  3,
  value__flag_id__field_descriptors,
  value__flag_id__field_indices_by_name,
  1,  value__flag_id__number_ranges,
  (ProtobufCMessageInit) value__flag_id__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor value__field_descriptors[2] =
{
  {
    "scalar",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Value, kind2_case),
    offsetof(Value, scalar),
    &scalar__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "complex",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Value, kind2_case),
    offsetof(Value, complex),
    &xs_complex__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned value__field_indices_by_name[] = {
  1,   /* field[1] = complex */
  0,   /* field[0] = scalar */
};
static const ProtobufCIntRange value__number_ranges[1 + 1] =
{
  { 7, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Value",
  "Value",
  "Value",
  "",
  sizeof(Value),
  2,
  value__field_descriptors,
  value__field_indices_by_name,
  1,  value__number_ranges,
  (ProtobufCMessageInit) value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scalar__field_descriptors[8] =
{
  {
    "the_null",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Scalar, kind_case),
    offsetof(Scalar, the_null),
    &xs_null__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Scalar, kind_case),
    offsetof(Scalar, bool_),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integer",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Scalar, kind_case),
    offsetof(Scalar, integer),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Scalar, kind_case),
    offsetof(Scalar, number),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Scalar, kind_case),
    offsetof(Scalar, string),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbol",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Scalar, kind_case),
    offsetof(Scalar, symbol),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bigint",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Scalar, kind_case),
    offsetof(Scalar, bigint),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "undefined",
    100,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Scalar, kind_case),
    offsetof(Scalar, undefined),
    &undefined__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scalar__field_indices_by_name[] = {
  6,   /* field[6] = bigint */
  1,   /* field[1] = bool */
  2,   /* field[2] = integer */
  3,   /* field[3] = number */
  4,   /* field[4] = string */
  5,   /* field[5] = symbol */
  0,   /* field[0] = the_null */
  7,   /* field[7] = undefined */
};
static const ProtobufCIntRange scalar__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 7, 5 },
  { 100, 7 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor scalar__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Scalar",
  "Scalar",
  "Scalar",
  "",
  sizeof(Scalar),
  8,
  scalar__field_descriptors,
  scalar__field_indices_by_name,
  3,  scalar__number_ranges,
  (ProtobufCMessageInit) scalar__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define uninitialized__field_descriptors NULL
#define uninitialized__field_indices_by_name NULL
#define uninitialized__number_ranges NULL
const ProtobufCMessageDescriptor uninitialized__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Uninitialized",
  "Uninitialized",
  "Uninitialized",
  "",
  sizeof(Uninitialized),
  0,
  uninitialized__field_descriptors,
  uninitialized__field_indices_by_name,
  0,  uninitialized__number_ranges,
  (ProtobufCMessageInit) uninitialized__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define undefined__field_descriptors NULL
#define undefined__field_indices_by_name NULL
#define undefined__number_ranges NULL
const ProtobufCMessageDescriptor undefined__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Undefined",
  "Undefined",
  "Undefined",
  "",
  sizeof(Undefined),
  0,
  undefined__field_descriptors,
  undefined__field_indices_by_name,
  0,  undefined__number_ranges,
  (ProtobufCMessageInit) undefined__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define xs_null__field_descriptors NULL
#define xs_null__field_indices_by_name NULL
#define xs_null__number_ranges NULL
const ProtobufCMessageDescriptor xs_null__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "XsNull",
  "XsNull",
  "XsNull",
  "",
  sizeof(XsNull),
  0,
  xs_null__field_descriptors,
  xs_null__field_indices_by_name,
  0,  xs_null__number_ranges,
  (ProtobufCMessageInit) xs_null__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xs_complex__field_descriptors[8] =
{
  {
    "self",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(XsComplex, has_self),
    offsetof(XsComplex, self),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reference",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XsComplex, kind_case),
    offsetof(XsComplex, reference),
    &reference__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XsComplex, kind_case),
    offsetof(XsComplex, instance),
    &instance__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "array",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XsComplex, kind_case),
    offsetof(XsComplex, array),
    &array__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XsComplex, kind_case),
    offsetof(XsComplex, code),
    &code__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accessor",
    37,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XsComplex, kind_case),
    offsetof(XsComplex, accessor),
    &accessor__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "home",
    41,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XsComplex, kind_case),
    offsetof(XsComplex, home),
    &home__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "callback",
    48,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XsComplex, kind_case),
    offsetof(XsComplex, callback),
    &callback__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xs_complex__field_indices_by_name[] = {
  5,   /* field[5] = accessor */
  3,   /* field[3] = array */
  7,   /* field[7] = callback */
  4,   /* field[4] = code */
  6,   /* field[6] = home */
  2,   /* field[2] = instance */
  1,   /* field[1] = reference */
  0,   /* field[0] = self */
};
static const ProtobufCIntRange xs_complex__number_ranges[8 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 13, 2 },
  { 16, 3 },
  { 20, 4 },
  { 37, 5 },
  { 41, 6 },
  { 48, 7 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor xs_complex__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "XsComplex",
  "XsComplex",
  "XsComplex",
  "",
  sizeof(XsComplex),
  8,
  xs_complex__field_descriptors,
  xs_complex__field_indices_by_name,
  8,  xs_complex__number_ranges,
  (ProtobufCMessageInit) xs_complex__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor array__field_descriptors[2] =
{
  {
    "size",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Array, has_size),
    offsetof(Array, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Array, n_items),
    offsetof(Array, items),
    &slot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned array__field_indices_by_name[] = {
  1,   /* field[1] = items */
  0,   /* field[0] = size */
};
static const ProtobufCIntRange array__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor array__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Array",
  "Array",
  "Array",
  "",
  sizeof(Array),
  2,
  array__field_descriptors,
  array__field_indices_by_name,
  1,  array__number_ranges,
  (ProtobufCMessageInit) array__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor reference__field_descriptors[1] =
{
  {
    "instance",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Reference, instance),
    &slot_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reference__field_indices_by_name[] = {
  0,   /* field[0] = instance */
};
static const ProtobufCIntRange reference__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor reference__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Reference",
  "Reference",
  "Reference",
  "",
  sizeof(Reference),
  1,
  reference__field_descriptors,
  reference__field_indices_by_name,
  1,  reference__number_ranges,
  (ProtobufCMessageInit) reference__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slot_opt__field_descriptors[2] =
{
  {
    "none",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SlotOpt, tag_case),
    offsetof(SlotOpt, none),
    &none__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "some",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SlotOpt, tag_case),
    offsetof(SlotOpt, some),
    &slot__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slot_opt__field_indices_by_name[] = {
  0,   /* field[0] = none */
  1,   /* field[1] = some */
};
static const ProtobufCIntRange slot_opt__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor slot_opt__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SlotOpt",
  "SlotOpt",
  "SlotOpt",
  "",
  sizeof(SlotOpt),
  2,
  slot_opt__field_descriptors,
  slot_opt__field_indices_by_name,
  1,  slot_opt__number_ranges,
  (ProtobufCMessageInit) slot_opt__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slot_list__field_descriptors[2] =
{
  {
    "none",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SlotList, tag_case),
    offsetof(SlotList, none),
    &nil__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "head",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SlotList, tag_case),
    offsetof(SlotList, head),
    &slot_list__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slot_list__field_indices_by_name[] = {
  1,   /* field[1] = head */
  0,   /* field[0] = none */
};
static const ProtobufCIntRange slot_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor slot_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SlotList",
  "SlotList",
  "SlotList",
  "",
  sizeof(SlotList),
  2,
  slot_list__field_descriptors,
  slot_list__field_indices_by_name,
  1,  slot_list__number_ranges,
  (ProtobufCMessageInit) slot_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define none__field_descriptors NULL
#define none__field_indices_by_name NULL
#define none__number_ranges NULL
const ProtobufCMessageDescriptor none__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "None",
  "None",
  "None",
  "",
  sizeof(None),
  0,
  none__field_descriptors,
  none__field_indices_by_name,
  0,  none__number_ranges,
  (ProtobufCMessageInit) none__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define nil__field_descriptors NULL
#define nil__field_indices_by_name NULL
#define nil__number_ranges NULL
const ProtobufCMessageDescriptor nil__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Nil",
  "Nil",
  "Nil",
  "",
  sizeof(Nil),
  0,
  nil__field_descriptors,
  nil__field_indices_by_name,
  0,  nil__number_ranges,
  (ProtobufCMessageInit) nil__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define instance__field_descriptors NULL
#define instance__field_indices_by_name NULL
#define instance__number_ranges NULL
const ProtobufCMessageDescriptor instance__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Instance",
  "Instance",
  "Instance",
  "",
  sizeof(Instance),
  0,
  instance__field_descriptors,
  instance__field_indices_by_name,
  0,  instance__number_ranges,
  (ProtobufCMessageInit) instance__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor code__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Code, has_code),
    offsetof(Code, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "closures",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Code, closures),
    &slot_opt__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned code__field_indices_by_name[] = {
  1,   /* field[1] = closures */
  0,   /* field[0] = code */
};
static const ProtobufCIntRange code__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor code__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Code",
  "Code",
  "Code",
  "",
  sizeof(Code),
  2,
  code__field_descriptors,
  code__field_indices_by_name,
  1,  code__number_ranges,
  (ProtobufCMessageInit) code__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor accessor__field_descriptors[2] =
{
  {
    "getter",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Accessor, getter),
    &slot_opt__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setter",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Accessor, setter),
    &slot_opt__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned accessor__field_indices_by_name[] = {
  0,   /* field[0] = getter */
  1,   /* field[1] = setter */
};
static const ProtobufCIntRange accessor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor accessor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Accessor",
  "Accessor",
  "Accessor",
  "",
  sizeof(Accessor),
  2,
  accessor__field_descriptors,
  accessor__field_indices_by_name,
  1,  accessor__number_ranges,
  (ProtobufCMessageInit) accessor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor home__field_descriptors[2] =
{
  {
    "object",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Home, object),
    &slot_opt__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "module",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Home, module),
    &slot_opt__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned home__field_indices_by_name[] = {
  1,   /* field[1] = module */
  0,   /* field[0] = object */
};
static const ProtobufCIntRange home__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor home__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Home",
  "Home",
  "Home",
  "",
  sizeof(Home),
  2,
  home__field_descriptors,
  home__field_indices_by_name,
  1,  home__number_ranges,
  (ProtobufCMessageInit) home__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor callback__field_descriptors[1] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Callback, has_address),
    offsetof(Callback, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned callback__field_indices_by_name[] = {
  0,   /* field[0] = address */
};
static const ProtobufCIntRange callback__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor callback__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Callback",
  "Callback",
  "Callback",
  "",
  sizeof(Callback),
  1,
  callback__field_descriptors,
  callback__field_indices_by_name,
  1,  callback__number_ranges,
  (ProtobufCMessageInit) callback__init,
  NULL,NULL,NULL    /* reserved[123] */
};
